### PR TITLE
Escape or URL encode paths where necessary

### LINKED ISSUE #155: Doesn't work if there are apostrophes in the file name.
Doesn't work if there are apostrophes in the file name.
I made hotfix in dl.php file line 116:

```
$archiveName = basename($archiveName);
$archiveName = encodePath($archiveName);
$archiveName = str_replace("%26apos%3B","%27",$archiveName);
```

And in svnlook.php file line 633:

```
	function svnCommandString($command, $path, $rev, $peg) {
		global $config;
		$s=encodePath($this->getSvnPath($path));
		$s=str_replace('%26apos%3B','%27',$s);
		return $config->getSvnCommand().$this->repConfig->svnCredentials().' '.$command.' '.($rev ? '-r '.$rev.' ' : '').quote($s.'@'.($peg ? $peg : ''));	
	}
```

But this is a very bad decision.

### PR DESCRIPTION
**Pull request by michael-o**
When running in non-MultiViews mode path passed from browser is prematurely
escaped for XML although it is still in use in PHP. This will result in two
issues:

* Broken paths are processed in PHP
* Data returned to users is broken or double escaped

This closes #155

### CODE REVIEW

File: include/setup.php [hunk 1]
```diff
@@ -496,8 +496,7 @@
 $vars['indexurl'] = $config->getURL('', '', 'index');
 $vars['validationurl'] = getFullURL($_SERVER['SCRIPT_NAME']).'?'.buildQuery($queryParams + array('template' => $template, 'language' => $language), '%26');
 
-// To avoid a possible XSS exploit, need to clean up the passed-in path first
-$path = !empty($_REQUEST['path']) ? escape($_REQUEST['path']) : null;
+$path = !empty($_REQUEST['path']) ? $_REQUEST['path'] : null;
```
Comment (ams-tschoening) [inline include/setup.php:499]: Removing `escape` without addressing all places where a path is forwarded 1:1 into HTML is problematic, as it will introduce XSS.

Comment (michael-o) [reply include/setup.php:499]: True, identifying them is hard. Its use is spread all over.

File: blame.php [hunk 2]
```diff
@@ -81,7 +81,8 @@
 
 $vars['rev'] = $rev;
 $vars['peg'] = $peg;
-$vars['path'] = escape($ppath);
+$vars['path'] = str_replace('%2F', '/', rawurlencode($ppath));
```
Comment (ams-tschoening) [inline blame.php:84]: This looks confusing to me: I would have expected `path` to be a plain path, not an encoded URL. What's the reason for doing so? Is `path` always used in some URL-context? Wouldn't it be better to distinguish the plain path from an encoded URL using different variable names, something like `urlPath` or `pathAsUrl` or alike? Pretty much like `safepath` currently.

Comment (michael-o) [reply blame.php:84]: I can explain that. If you look at the tempates: `websvn:path` is solely used iwth `href` attributes which require URI encoding. Paths which appear as text are prefixed with `safe` since they aren't usable in `href` attributes. Thhe code did not properly address this and assumed that files would be 7 bit ASCII only.

Comment (ams-tschoening) [reply blame.php:84]: So how about renaming `path` to something mentioning it to be a URL instead? Too risky/too much work or simple global search&replace? `safepath` seems badly named as well and is more like a `htmlPath`.

**Review by ams-tschoening — APPROVED** [review]
I won't have the time to test this in detail, so let's end naming discussions and use what works for you.

**Comment by michael-o** [comment]
> I won't have the time to test this in detail, so let's end naming discussions and use what works for you.

I did testing with all templates and affected PHP files with multi views and non-MV, I hope I haven't miss anything. I will leave the reporter a few more days to test and then will merge.
